import type { Metadata } from 'next'

import './globals.css'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen h-full flex items-center justify-center p-7 lg:p-0'>{children}</body>
    </html >
  )
}
